version: "3.9"

services:
  mysql:
    image: mysql:8.0.28
    container_name: mysql-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sabakan
      TZ: "Asia/Tokyo"
    volumes:
      - ./my.cnf:/etc/mysql/conf.d/my.cnf

  adminer:
    image: adminer
    ports:
      - 8080:8080
